site_name: Toured Wiki
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
  palette:
    - scheme: default
plugins:
  - search
nav:
  - Home: index.md
  - Getting Started: ReadMe.md
  - Roadmap: roadmap.md
